# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 01:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('decimal_separator', models.CharField(max_length=5)),
                ('currency_id', models.CharField(max_length=25)),
                ('time_zone', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pa\xeds',
                'verbose_name_plural': 'Pa\xedses',
            },
        ),
        migrations.CreateModel(
            name='MeliAccount',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False, verbose_name='id de mercado libre')),
                ('temporal_code', models.CharField(max_length=255)),
                ('temporal_access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('site_id', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=255)),
                ('country_id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meli_account', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de mercado libre')),
            ],
            options={
                'verbose_name': 'cuenta de mercado libre',
                'verbose_name_plural': 'cuentas de mercado libre',
            },
        ),
        migrations.CreateModel(
            name='MeliCar',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=70)),
                ('subtitle', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.TextField()),
                ('category_id', models.CharField(max_length=100)),
                ('official_store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('base_price', models.IntegerField()),
                ('original_price', models.IntegerField(null=True)),
                ('currency_id', models.CharField(max_length=10)),
                ('initial_quantity', models.IntegerField(default=1)),
                ('available_quantity', models.IntegerField(default=1)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('buying_mode', models.CharField(default='classified', max_length=50)),
                ('listing_type_id', models.CharField(default='free', max_length=50)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('stop_time', models.DateTimeField()),
                ('condition', models.CharField(default='used', max_length=150)),
                ('video_id', models.CharField(blank=True, max_length=150)),
                ('accepts_mercadopago', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='mercadolibre.MeliAccount')),
            ],
        ),
        migrations.CreateModel(
            name='MeliCarPictures',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('secure_url', models.URLField(null=True)),
                ('size', models.CharField(max_length=100)),
                ('max_size', models.CharField(max_length=100)),
                ('quality', models.CharField(blank=True, max_length=100, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='mercadolibre.MeliCar')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mercadolibre.Country')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='mercadolibre.State'),
        ),
    ]
