# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 22:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeliAccount',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False, verbose_name='id de mercado libre')),
                ('temporal_code', models.CharField(max_length=255)),
                ('temporal_access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('site_id', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=255)),
                ('country_id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meli_account', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de mercado libre')),
            ],
            options={
                'verbose_name': 'cuenta de mercado libre',
                'verbose_name_plural': 'cuentas de mercado libre',
            },
        ),
        migrations.CreateModel(
            name='MLCity',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de ciudad ML')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='MLCountry',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre Pais de ML')),
                ('decimal_separator', models.CharField(max_length=5)),
                ('currency_id', models.CharField(max_length=25)),
                ('time_zone', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='MLState',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de estado ML')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mercadolibre.MLCountry')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AddField(
            model_name='mlcity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='mercadolibre.MLState'),
        ),
    ]
